<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1552014474725" stop="1552014474874">
  <name>scripts.test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1552014474725" status="passed" stop="1552014474759">
      <name>TestLogin.test_login1</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4268-MainThread"/>
        <label name="host" value="DESKTOP-CU17CM9"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1552014474763" status="passed" stop="1552014474768">
      <name>TestLogin.test_login2</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4268-MainThread"/>
        <label name="host" value="DESKTOP-CU17CM9"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1552014474772" status="failed" stop="1552014474874">
      <name>TestLogin.test_login3</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x0000021BA700EF60&gt;

    def test_login3(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4268-MainThread"/>
        <label name="host" value="DESKTOP-CU17CM9"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
